meta_product_name: "Shinier"
meta_title: "Shinier - Ne reste plus dans l'ombre"
meta_description: "Shinier est un site collaboratif où chacun peut accéder à un groupe solidaire autour de sa pathologie."
meta_image: "logo-shinier.svg"
twitter_account: "@shinier10"
